### ISSUE TITLE
알람 기능 구현

### ISSUE THREAD

**Issue by dmsdnWkd1234** [modern-agile-team/ModernWorld-Front#100]
## 개요
- SSE를 통한 알람 기능 구현
- 알람 퍼블리싱

## 작업내용
- [ ] 퍼블리싱
- [x] SSE 이벤트 객체 생성
- [ ] 알람 기능 구현

## 참고
- https://velog.io/@oluzr/Next.js14-SSE%EB%A5%BC-%ED%86%B5%ED%95%9C-%EC%95%8C%EB%A6%BC-%EA%B5%AC%ED%98%84
-

**Comment by chamjin** [comment]
Branch feat/알람_기능_구현/#100 created for issue: 알람 기능 구현

**Comment by chamjin** [comment]
Could not create branch `feat/알람_기능_구현/#100` due to: Reference update failed - https://docs.github.com/rest/git/refs#create-a-reference
