### ISSUE TITLE
방 퍼블리싱 및 기능

### ISSUE THREAD

**Issue by dmsdnWkd1234** [modern-agile-team/ModernWorld-Front#62]
## 개요
- 방 구역 쪼개기
- 데이터 불러온거 배치하기

## 작업내용
- [ ] grid로 방 구역 나누기
- [ ] 인벤토리 api 불러와서 배치하기

## 참고
-
-

**Comment by chamjin** [comment]
Could not create branch `/방_퍼블리싱_및_기능/#62` due to: refs/heads//방_퍼블리싱_및_기능/#62 is not a valid ref name. - https://docs.github.com/rest/git/refs#create-a-reference

**Comment by chamjin** [comment]
Could not create branch `/방_퍼블리싱_및_기능/#62` due to: refs/heads//방_퍼블리싱_및_기능/#62 is not a valid ref name. - https://docs.github.com/rest/git/refs#create-a-reference
